source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.2.4'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'foundation-rails', '6.3.0.0'
gem 'devise', '3.5.5'
gem 'dotenv-rails'
gem 'simple_form'
gem 'carrierwave'
gem 'fog'
gem 'kaminari'
gem 'font-awesome-sass'
gem 'jquery-slick-rails'

group :development, :test do
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'launchy'
  gem 'faker'
  gem 'factory_girl'
  gem 'valid_attribute'
  gem 'shoulda'
  gem 'database_cleaner'
end
